name: Java CI with Tests and Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compile Java Program
        run: |
          mkdir -p classes
          javac -cp .:junit-platform-console-standalone-1.10.0.jar -d classes App.java AppTest.java

      - name: Run Tests with Coverage
        run: |
          java -javaagent:jacocoagent.jar=destfile=jacoco.exec,output=file -cp classes:junit-platform-console-standalone-1.10.0.jar org.junit.platform.console.ConsoleLauncher --scan-class-path

      - name: Generate Coverage Report
        run: |
          java -jar jacococli.jar report jacoco.exec --classfiles classes --sourcefiles . --html coverage-report

      - name: Upload Coverage Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage-report
